### ISSUE TITLE
执行外部jar目录报错

### ISSUE THREAD

**Issue by gongxufan** [didi/JuShaTa#6]
java.lang.ClassCastException: class org.springframework.boot.context.event.ApplicationStartingEvent cannot be cast to class org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent (org.springframework.boot.context.event.ApplicationStartingEvent and org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent are in unnamed module of loader 'app')
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
	at com.didiglobal.jushata.springboot.JushataSpringBootModule.refreshContext(JushataSpringBootModule.java:146)
	at com.didiglobal.jushata.springboot.JushataSpringBootModule.loadJushataModule(JushataSpringBootModule.java:118)
	at com.didiglobal.jushata.springboot.JushataSpringBootModule.start(JushataSpringBootModule.java:60)
	at com.didiglobal.jushata.springboot.JushataSpringBootModuleLoader.start(JushataSpringBootModuleLoader.java:132)
	at com.didiglobal.jushata.springboot.JushataSpringBootModuleLoader.load(JushataSpringBootModuleLoader.java:46)
	at com.didiglobal.jushata.springboot.JushataApplication.load(JushataApplication.java:55)
	at com.didiglobal.jushata.springboot.JushataApplication.run(JushataApplication.java:41)
	at com.didiglobal.jushata.springboot.JushataApplicationReadyEventListener.onApplicationEvent(JushataApplicationReadyEventListener.java:12)
	at com.didiglobal.jushata.springboot.JushataApplicationReadyEventListener.onApplicationEvent(JushataApplicationReadyEventListener.java:6)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.didiglobal.jushata.sample.SampleApplication.main(SampleApplication.java:15)

**Comment by gongxufan** [comment]
jdk版本问题
